### ISSUE TITLE
simple_fast

### ISSUE THREAD

**Issue by FlyFlySheep** [dsgt-birdclef/birdclef-2023#101]
As I downloaded the code from github, I tried with the notebook given. And I ran the code python -m birdclef.workflows.motif extract
As it ran to 100%, it threw an error below :
ModuleNotFoundError: No module named 'simple'
So how can I solve this problem? Thank you.

**Comment by acmiyaguchi** [comment]
A lot of the notebooks were done as scratch work essentially. You'll probably need this library at the very least: https://github.com/acmiyaguchi/simple-fast-python
