### ISSUE TITLE
Transcode all training audio from ogg to mp3 for browser consumption

### ISSUE THREAD

**Issue by acmiyaguchi** [dsgt-birdclef/birdclef-2023#25]
Ogg vorbis is a great format (patent unencumbered, relatively high fidelity lossy encoder), but there are issues playing ogg files from safari. In order to support an interactive dashboard of audio files, we should re-encode all of the audio files into mp3. Given that our models should be robust to environmental noise, it should be fine to introduce encoding artifacts into the process.

**Comment by acmiyaguchi** [comment]
I'll have you work on this workflow as a first task, which may be useful to have https://github.com/dsgt-birdclef/birdclef-2023/issues/28 up and running at first (but certainly not necessary). I imagine this as a luigi workflow that:

- downloads a species from GCS
- transcodes the audio using a script wrapping ffmpeg in a docker container
- uploading the transcoded audio into another directory (or bucket) in GCS

See https://github.com/dsgt-birdclef/birdclef-2023/blob/5e9772d30ae3863a8cfddeab76b8492d4decb482/scripts/mixit_ogg_wrapper.py as an example of a wrapper to convert ogg to wav using ffmpeg. 

It may be useful to try running one of the existing workflows to see how luigi works -- this is sorely under-documented so I will add this as a task for me to do.

**Comment by acmiyaguchi** [comment]
@ChrisHayduk Just curious what your progress has been here - is this too big of a task, or are there problem points that have presented themselves?

**Comment by ChrisHayduk** [comment]
@acmiyaguchi Had a heavy week at work so getting to this tonight and tomorrow. Right now I have a small Python script to convert from ogg to mp3 ready to go. Just working on integrating this into a Luigi workflow - will update the standup doc with any issues I run into while putting this together.

**Comment by ChrisHayduk** [comment]
@acmiyaguchi Small Luigi script I've been testing locally here:
[https://github.com/dsgt-birdclef/birdclef-2023/blob/ogg-to-mp3/workflows/ogg_to_mp3.py](https://github.com/dsgt-birdclef/birdclef-2023/blob/ogg-to-mp3/workflows/ogg_to_mp3.py)

Let's go over it in tomorrow's stand up and if the functionality looks good, then I'll set it up with Google Cloud bucket access.

**Comment by acmiyaguchi** [comment]
> @acmiyaguchi Small Luigi script I've been testing locally here: https://github.com/dsgt-birdclef/birdclef-2023/blob/ogg-to-mp3/workflows/ogg_to_mp3.py

Ooh very nice, [pydub](https://github.com/jiaaro/pydub) is an ffmpeg wrapper it looks like? We should set the parameters on this explicitly. I would say 128kpbs VBR, which look like q5 in this guide: https://trac.ffmpeg.org/wiki/Encode/MP3

Also, feel free to open up a draft PR to share you code -- it's easier to discuss things inline, and we don't have to worry about accidentally adding things in a half-baked state.

**Comment by ChrisHayduk** [comment]
Done on both:

- Added the encoding parameter to produce VBR MP3 audio at an average bitrate of 130 kbit/s using the parameter "q:a 5"
- Created a PR here: [https://github.com/dsgt-birdclef/birdclef-2023/pull/46](https://github.com/dsgt-birdclef/birdclef-2023/pull/46)
