### ISSUE TITLE
Create onboarding documentation for new team members

### ISSUE THREAD

**Issue by acmiyaguchi** [dsgt-birdclef/birdclef-2023#27]
There is quite a bit of context to take in when first joining the project. The goal here is to provide a checklist and documentation that can be used to bring someone up to speed relatively quickly (1-2 weeks).

- [x] Add a wiki page with information on getting started with GCP
- [ ] Record a series of videos going over logical pieces of the codebase: luigi, sveltekit, birdnet, mixit
- [x] Provide links to papers that are relevant to the project
- [x] Make sure that new members make a contribution within the first 2 weeks of joining

**Comment by acmiyaguchi** [comment]
@zemm16 As you go through the process of getting situated, it would be great if you could also help update the https://github.com/dsgt-birdclef/birdclef-2023/wiki/Onboarding page. It's bare at the moment, but it should be the goto to point folks.

**Comment by zemm16** [comment]
Still trying to find a good Recurrent Neural Network tutorial (for anyone who doesn't know sequential models yet). I referenced the text book from the Deep Learning Class. RNN's are pretty straightforward and so I didn't reference any extra material during the class, and this chapter is 40 pages, which is a bit excessive. I am thinking there is a better tutorial out there that is a bit shorter.

**Comment by acmiyaguchi** [comment]
The pytorch tutorials tend to be good, maybe something on lstm or transformers directly could be good reference?

- https://pytorch.org/tutorials/beginner/nlp/sequence_models_tutorial.html
- https://pytorch.org/tutorials/beginner/transformer_tutorial.html

**Comment by zemm16** [comment]
Yeah, Pytorch tutorials are really good, I will put some good ones in the onboarding as well.

**Comment by GQW19** [comment]
I added a few tutorials here that I noticed were very helpful from PyTorch-LIghtning's tutorial set. They include some Notebook tutorials from University of Amsterdam on Deep Learning and Transformers that are really helpful.
