### ISSUE TITLE
Implement a luigi script for birdnet cluster plots

### ISSUE THREAD

**Issue by acmiyaguchi** [dsgt-birdclef/birdclef-2023#54]
This notebook was used to generate the birdnet clustering plots: https://github.com/dsgt-birdclef/birdclef-2023/blob/main/notebooks/acm-20230122-01-birdnet-cluster-nn-write.ipynb

We currently take the 20 most common species -- mostly because it takes a long time to generate these plots. It might be helpful to create a luigi task that parallelizes based on available species, and then syncs up the directories into a GCS bucket. It should also generate a manifest.

**Comment by acmiyaguchi** [comment]
@nzhongathan would you be interested in taking this on after you finish with #23? It should give a bit of experience with luigi, and extend the available set of species.

**Comment by nzhongathan** [comment]
sure I can take this issue. I will finish #23 by the end of this week so I will start on this around then
