### ISSUE TITLE
Add task history to luigi scheduler

### ISSUE THREAD

**Issue by acmiyaguchi** [dsgt-birdclef/birdclef-2023#63]
The current luigi scheduler does not keep a history of jobs, which makes it kind of tricky to look through what had run. It's not a super important thing, but it would be nice to figure out how to configure the scheduler to keep history.

**Comment by ChrisHayduk** [comment]
This should help here: https://luigi.readthedocs.io/en/stable/central_scheduler.html#enabling-task-history

**Comment by acmiyaguchi** [comment]
I've added this, but the task history server is not very optimized and slows the entire thing down. This should be self-documented in the code under the ansible role.
