### ISSUE TITLE
Find background noise dataset to interpolate birdcalls with

### ISSUE THREAD

**Issue by acmiyaguchi** [dsgt-birdclef/birdclef-2023#70]
We need some backing tracks that we can mix into our datasets that can be used to pad the datasets. This is because there are tracks that are less than 10 seconds long.

**Comment by nzhongathan** [comment]
BirdCLEF2021 1st Place Solution -> Used freefield1010 dataset to build a nocall detector; can either look into freefield1001 or using the nocall detector on BirdCLEF data for background tracks
https://www.kaggle.com/c/birdclef-2021/discussion/243927
https://github.com/namakemono/kaggle-birdclef-2021/blob/master/share_solution/working/build_nocall_detector.ipynb

BirdCLEF2022 1st Place Model -> Used esc50 dataset and nocall from soundscapes of BirdCLEF2021
https://www.kaggle.com/datasets/mmoreaux/environmental-sound-classification-50

Most ones I've seen are freefield1010 (10 sec audio data) and nocall from past BirdCLEF

freefield1010 -> https://dcase.community/challenge2018/task-bird-audio-detection#audio-datasets
Development dataset seem to be labelled so we can either just take the labelled nocall audio tracks from here or use this to create a nocall detector and find the nocalls from BirdCLEF data (basically the first approach)
